import clsx from "clsx";

export const buttonStyle = {
    base: clsx(
        "group/button",
        "inline-flex",
        "shrink-0",
        "items-center",
        "justify-center",
        "rounded-lg",
        "border",
        "border-transparent",
        "bg-clip-padding",
        "text-sm",
        "font-medium",
        "whitespace-nowrap",
        "transition-all",
        "outline-none",
        "select-none",
        "cursor-pointer",
        "focus-visible:border-ring",
        "focus-visible:ring-3",
        "focus-visible:ring-ring/50",
        "active:not-aria-[haspopup]:translate-y-px",
        "disabled:pointer-events-none",
        "disabled:opacity-50",
        "aria-invalid:border-button-invalid-border",
        "aria-invalid:ring-3",
        "aria-invalid:ring-button-invalid-ring",
        "[&_svg]:pointer-events-none",
        "[&_svg]:shrink-0",
        "[&_svg:not([class*='size-'])]:size-4",
    ),

    variants: {
        default: clsx(
            "bg-primary",
            "text-primary-foreground",
            "hover:bg-primary/80",
        ),
        outline: clsx(
            "border-button-outline-border",
            "bg-button-outline-bg",
            "hover:bg-button-outline-hover-bg",
            "hover:text-foreground",
            "aria-expanded:bg-button-outline-hover-bg",
            "aria-expanded:text-foreground",
        ),
        secondary: clsx(
            "bg-secondary",
            "text-secondary-foreground",
            "hover:bg-[color-mix(in_oklch,var(--secondary),var(--foreground)_5%)]",
            "aria-expanded:bg-secondary",
            "aria-expanded:text-secondary-foreground",
        ),
        ghost: clsx(
            "hover:bg-button-ghost-hover-bg",
            "hover:text-foreground",
            "aria-expanded:bg-button-ghost-hover-bg",
            "aria-expanded:text-foreground",
        ),
        destructive: clsx(
            "bg-button-destructive-bg",
            "text-danger-text-color",
            "hover:bg-button-destructive-hover-bg",
            "focus-visible:border-danger-text-color/40",
            "focus-visible:ring-button-destructive-ring",
        ),
        link: clsx("text-primary", "underline-offset-4", "hover:underline"),
    },

    sizes: {
        default: clsx(
            "h-8",
            "gap-1.5",
            "px-2.5",
            "has-data-[icon=inline-end]:pr-2",
            "has-data-[icon=inline-start]:pl-2",
        ),
        xs: clsx(
            "h-6",
            "gap-1",
            "rounded-[min(var(--radius-md),10px)]",
            "px-2",
            "text-xs",
            "in-data-[slot=button-group]:rounded-lg",
            "has-data-[icon=inline-end]:pr-1.5",
            "has-data-[icon=inline-start]:pl-1.5",
            "[&_svg:not([class*='size-'])]:size-3",
        ),
        sm: clsx(
            "h-7",
            "gap-1",
            "rounded-[min(var(--radius-md),12px)]",
            "px-2.5",
            "text-[0.8rem]",
            "in-data-[slot=button-group]:rounded-lg",
            "has-data-[icon=inline-end]:pr-1.5",
            "has-data-[icon=inline-start]:pl-1.5",
            "[&_svg:not([class*='size-'])]:size-3.5",
        ),
        lg: clsx(
            "h-9",
            "gap-1.5",
            "px-2.5",
            "has-data-[icon=inline-end]:pr-2",
            "has-data-[icon=inline-start]:pl-2",
        ),
        icon: clsx("size-8"),
        "icon-xs": clsx(
            "size-6",
            "rounded-[min(var(--radius-md),10px)]",
            "in-data-[slot=button-group]:rounded-lg",
            "[&_svg:not([class*='size-'])]:size-3",
        ),
        "icon-sm": clsx(
            "size-7",
            "rounded-[min(var(--radius-md),12px)]",
            "in-data-[slot=button-group]:rounded-lg",
        ),
        "icon-lg": clsx("size-9"),
    },
};
