# Generated by Django 6.0.6 on 2026-06-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_facility_venue_address_venue_facilities_venueimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='price_per_hour',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='facilities',
        ),
        migrations.AddField(
            model_name='facility',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='venues.venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_image', models.ImageField(upload_to='media/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('capacity', models.IntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='venues.venue')),
            ],
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
