# Generated by Django 6.0.6 on 2026-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_rename_city_venue_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='choice',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
