# Generated by Django 6.0.6 on 2026-06-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_facility_choice_alter_facility_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holly_day', models.DecimalField(decimal_places=5, max_digits=10)),
                ('seasons_day', models.DecimalField(decimal_places=5, max_digits=10)),
                ('night', models.DecimalField(decimal_places=5, max_digits=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='venues.venue')),
            ],
        ),
    ]
