# Generated by Django 6.0.6 on 2026-06-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='holly_day',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='price',
            name='night',
        ),
        migrations.RemoveField(
            model_name='price',
            name='seasons_day',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price',
        ),
        migrations.AddField(
            model_name='facility',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='choice',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='price_verision',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='choice',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
