# Generated by Django 6.0.6 on 2026-06-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_rename_holly_day_price_amount_remove_price_night_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('video', models.FileField(upload_to='media/videos/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
