# Generated by Django 6.0.6 on 2026-06-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_venuemedia_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemedia',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='venues.venue'),
        ),
    ]
