# Generated by Django 6.0.6 on 2026-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
