# Generated by Django 6.0.6 on 2026-06-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
