# Generated by Django 5.2.12 on 2026-06-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("password_hash", models.TextField(blank=True, null=True)),
                ("otp_hash", models.TextField()),
                (
                    "method",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("PHONE", "Phone")], max_length=20
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "signup_requests",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("avatar_url", models.TextField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("venue", "Venue"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["email"], name="idx_users_email"),
                    models.Index(fields=["phone"], name="idx_users_phone"),
                    models.Index(fields=["role"], name="idx_users_role"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email__isnull", False),
                            ("phone__isnull", False),
                            _connector="OR",
                        ),
                        name="must_have_contact",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("GOOGLE", "Google"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("password_hash", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_accounts",
                "indexes": [
                    models.Index(
                        fields=["provider"], name="idx_auth_accounts_provider"
                    ),
                    models.Index(
                        fields=["provider_user_id"], name="idx_auth_acct_provider_uid"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="uq_auth_accounts_provider_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OtpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("otp_hash", models.TextField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("EMAIL_CHANGE", "Email Change"),
                            ("PHONE_CHANGE", "Phone Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_requests",
                "indexes": [
                    models.Index(
                        fields=["destination"], name="idx_otp_requests_destination"
                    )
                ],
            },
        ),
    ]
