"""removed test model

Revision ID: 63002df47126
Revises: cebfce97615d
Create Date: 2026-07-12 22:02:35.049177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63002df47126'
down_revision: Union[str, Sequence[str], None] = 'cebfce97615d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users1_email'), table_name='users1')
    op.drop_table('users1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users1_pkey'))
    )
    op.create_index(op.f('ix_users1_email'), 'users1', ['email'], unique=True)
    # ### end Alembic commands ###
