import clsx from "clsx";

export const venueStyle = {
    pageWrapper: clsx("ml-6", "mt-2"),
    formBox: clsx("grid", "gap-6", "lg:grid-cols-[1.2fr_1fr]"),
    basicInfoCard: clsx(
        "rounded-3xl",
        "border",
        "border-slate-200",
        "bg-white",
        "p-6",
        "shadow-sm",
        "lg:p-8",
    ),
    card: clsx(
        "rounded-3xl",
        "border",
        "border-slate-200",
        "bg-white",
        "p-6",
        "shadow-sm",
        "lg:p-8",
    ),
    headerWrapper: clsx("mb-6", "flex", "items-center", "gap-3"),
    headerIcon: clsx("h-6", "w-6", "text-teal-600"),
    headerTitle: clsx("text-lg", "font-semibold", "text-slate-900"),
    fieldGrid: clsx("grid", "gap-6", "md:grid-cols-2"),
    rowGrid3: clsx("grid", "gap-4", "md:grid-cols-3"),
    rowGrid2: clsx("grid", "gap-4", "md:grid-cols-2"),
    rowWrapper: clsx("mt-4"),
    label: clsx("mb-2", "block", "text-sm", "font-medium", "text-slate-700"),
    input: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "px-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
        "sm:h-14",
    ),
    select: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "px-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
        "sm:h-14",
    ),
    textarea: clsx(
        "w-full",
        "resize-none",
        "rounded-xl",
        "border",
        "border-slate-200",
        "p-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
    ),
    descriptionWrapper: clsx("mt-6"),
    charCounter: clsx("mt-2", "text-right", "text-xs", "text-slate-400"),
    amenitiesGrid: clsx(
        "grid",
        "gap-y-4",
        "gap-x-6",
        "sm:grid-cols-2",
        "lg:grid-cols-3",
    ),
    checkboxLabel: clsx(
        "flex",
        "cursor-pointer",
        "items-center",
        "gap-3",
        "text-sm",
        "text-slate-700",
    ),
    checkbox: clsx(
        "h-4",
        "w-4",
        "rounded",
        "border-slate-300",
        "text-teal-600",
        "focus:ring-teal-500",
    ),
    buttonSecondary: clsx(
        "mt-5",
        "inline-flex",
        "items-center",
        "gap-2",
        "rounded-xl",
        "border",
        "border-teal-200",
        "bg-white",
        "px-5",
        "py-3",
        "text-sm",
        "font-medium",
        "text-teal-700",
        "transition",
        "hover:bg-teal-50",
        "cursor-pointer",
    ),
    uploadZone: clsx(
        "flex",
        "h-28",
        "cursor-pointer",
        "flex-col",
        "items-center",
        "justify-center",
        "rounded-2xl",
        "border-2",
        "border-dashed",
        "border-slate-300",
        "transition",
        "hover:border-teal-500",
        "hover:bg-teal-50/30",
    ),
    uploadIcon: clsx("mb-2", "h-7", "w-7", "text-teal-600"),
    uploadText: clsx("text-sm", "font-medium", "text-slate-900"),
    uploadSubtext: clsx("mt-1", "text-xs", "text-slate-500"),
    galleryLabel: clsx("mb-3", "text-sm", "font-medium", "text-slate-700"),
    galleryGrid: clsx("grid", "grid-cols-3", "gap-3", "sm:grid-cols-5"),
    galleryAddButton: clsx(
        "flex",
        "h-16",
        "w-full",
        "items-center",
        "justify-center",
        "rounded-xl",
        "border-2",
        "border-dashed",
        "border-slate-300",
        "transition",
        "hover:border-teal-500",
        "hover:bg-teal-50/30",
    ),
    galleryAddIcon: clsx("h-5", "w-5", "text-slate-500"),
    headerSubtitle: clsx("mt-1", "text-sm", "text-slate-500"),
    searchWrapper: clsx("relative", "mb-4"),
    searchIcon: clsx(
        "absolute",
        "left-3",
        "top-1/2",
        "h-4",
        "w-4",
        "-translate-y-1/2",
        "text-slate-400",
    ),
    searchInput: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "pl-10",
        "pr-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
        "sm:h-14",
    ),
    mapBox: clsx(
        "h-[320px]",
        "overflow-hidden",
        "rounded-xl",
        "border",
        "border-slate-200",
        "bg-slate-100",
        "lg:h-[380px]",
    ),
    mapTextWrapper: clsx("flex", "h-full", "items-center", "justify-center"),
    mapText: clsx("text-sm", "text-slate-500"),
    mapHint: clsx("mt-2", "text-xs", "text-slate-500"),
    readOnlyInput: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "bg-slate-50",
        "px-4",
        "text-sm",
        "text-slate-500",
        "outline-none",
        "sm:h-14",
    ),
    coordinatesGrid: clsx("mt-4", "grid", "gap-4", "sm:grid-cols-2"),
    fieldSpacing: clsx("mt-4"),
    actionsContainer: clsx(
        "sticky",
        "bottom-0",
        "z-20",
        "mt-6",
        "rounded-3xl",
        "border",
        "border-slate-200",
        "bg-white",
        "p-4",
        "shadow-sm",
    ),
    actionsWrapper: clsx(
        "flex",
        "flex-col-reverse",
        "gap-3",
        "sm:flex-row",
        "sm:justify-end",
    ),
    buttonSaveDraft: clsx(
        "h-12",
        "rounded-xl",
        "border",
        "border-teal-600",
        "px-6",
        "text-sm",
        "font-semibold",
        "text-teal-600",
        "transition",
        "hover:bg-teal-50",
        "cursor-pointer",
        "sm:h-14",
    ),
    buttonSaveContinue: clsx(
        "h-12",
        "rounded-xl",
        "bg-teal-600",
        "px-6",
        "text-sm",
        "font-semibold",
        "text-white",
        "transition",
        "hover:bg-teal-700",
        "cursor-pointer",
        "sm:h-14",
    ),
    listvenuecontainer: clsx(
        "mx-4",
        "mt-4",
        "grid",
        "gap-4",
        "[grid-template-columns:repeat(auto-fill,minmax(280px,1fr))]",
    ),
    flexContainer: clsx("flex"),
    mainSection: clsx("flex-1"),
    loadingText: clsx("text-center", "py-10", "w-full", "text-gray-500"),
    errorText: clsx("text-center", "py-10", "w-full", "text-red-500"),
    emptyText: clsx("text-center", "py-10", "w-full", "text-gray-500"),
    photoGrid: clsx("grid", "gap-4"),
    coverPreview: clsx(
        "relative",
        "h-[200px]",
        "w-full",
        "rounded-lg",
        "overflow-hidden",
        "border",
        "border-slate-200",
    ),
    coverImg: clsx("h-full", "w-full", "object-cover"),
    coverRemoveBtn: clsx(
        "absolute",
        "top-2",
        "right-2",
        "bg-red-600",
        "text-white",
        "rounded-full",
        "px-2",
        "py-1",
        "text-xs",
        "hover:bg-red-700",
        "transition",
        "cursor-pointer",
    ),
    coverBadge: clsx(
        "absolute",
        "bottom-2",
        "left-2",
        "bg-black/60",
        "text-white",
        "text-xs",
        "px-2",
        "py-0.5",
        "rounded",
    ),
    galleryThumb: clsx(
        "relative",
        "h-16",
        "w-16",
        "md:h-20",
        "md:w-20",
        "rounded-lg",
        "overflow-hidden",
        "border",
        "border-slate-200",
    ),
    galleryThumbImg: clsx("h-full", "w-full", "object-cover"),
    galleryRemoveBtn: clsx(
        "absolute",
        "top-0.5",
        "right-0.5",
        "bg-red-600",
        "text-white",
        "rounded-full",
        "w-4",
        "h-4",
        "flex",
        "items-center",
        "justify-center",
        "text-[10px]",
        "hover:bg-red-700",
        "transition",
        "cursor-pointer",
    ),
    slotInput: clsx(
        "h-10",
        "w-full",
        "rounded-lg",
        "border",
        "border-slate-200",
        "bg-white",
        "px-3",
        "text-xs",
        "outline-none",
        "focus:border-teal-600",
        "focus:ring-1",
        "focus:ring-teal-100",
    ),
    pricingInput: clsx(
        "h-8",
        "w-full",
        "rounded-md",
        "border",
        "border-slate-200",
        "px-2",
        "text-xs",
        "outline-none",
        "focus:border-teal-600",
    ),
    addTierBtn: clsx(
        "mt-3",
        "inline-flex",
        "items-center",
        "gap-1",
        "text-[11px]",
        "font-semibold",
        "text-teal-600",
        "hover:text-teal-700",
        "transition",
        "cursor-pointer",
    ),
    addSlotBtn: clsx(
        "inline-flex",
        "items-center",
        "gap-2",
        "rounded-xl",
        "border",
        "border-teal-200",
        "bg-white",
        "px-4",
        "py-2.5",
        "text-xs",
        "font-semibold",
        "text-teal-700",
        "transition",
        "hover:bg-teal-50",
        "cursor-pointer",
    ),
    slotCard: clsx(
        "mb-6",
        "rounded-2xl",
        "border",
        "border-slate-200",
        "bg-slate-50/40",
        "p-4",
        "lg:p-6",
        "relative",
    ),
    slotCardHeader: clsx("mb-4", "flex", "items-center", "justify-between"),
    slotCardTitle: clsx("text-sm", "font-semibold", "text-teal-700"),
    removeSlotBtn: clsx(
        "flex",
        "items-center",
        "gap-1",
        "text-xs",
        "font-medium",
        "text-red-600",
        "hover:text-red-800",
        "transition",
        "cursor-pointer",
    ),
    slotInputsGrid: clsx("grid", "gap-4", "sm:grid-cols-2", "md:grid-cols-3"),
    slotFieldLabel: clsx("mb-1", "block", "text-xs", "font-medium", "text-slate-600"),
    slotSectionHeader: clsx("mt-4", "flex", "items-center", "gap-2"),
    slotSectionTitle: clsx("flex", "items-center", "gap-2"),
    slotSectionSubtitle: clsx("text-xs", "text-slate-500", "mt-1"),
    slotSectionHeading: clsx("font-semibold", "text-slate-800"),
    customPricingToggle: clsx("mt-4", "flex", "items-center", "gap-2"),
    customPricingLabel: clsx("text-xs", "font-medium", "text-slate-700", "cursor-pointer"),
    customPricingBox: clsx("mt-4", "max-w-xs"),
    flatPricingBox: clsx(
        "mt-4",
        "rounded-xl",
        "border",
        "border-slate-200/60",
        "bg-white",
        "p-4",
    ),
    flatPricingTitle: clsx("text-xs", "font-semibold", "text-slate-700", "block", "mb-3"),
    tierRow: clsx("flex", "items-center", "gap-2", "sm:gap-3"),
    tierGrid: clsx("grid", "flex-1", "grid-cols-3", "gap-2"),
    tierFieldLabel: clsx("mb-0.5", "block", "text-[10px]", "text-slate-500"),
    removeTierBtn: clsx(
        "mt-4",
        "p-1",
        "text-slate-400",
        "hover:text-red-600",
        "transition",
        "cursor-pointer",
    ),
    slotSectionWrapper: clsx("mt-4"),
    slotSectionTopBar: clsx("mb-4", "flex", "items-center", "justify-between"),
    tiersSpaceY: clsx("space-y-2"),
    sectionDivider: clsx("my-6", "border-slate-200"),
    categoriesWrapper: clsx("mt-4"),
    categoriesGrid: clsx("grid", "grid-cols-2", "md:grid-cols-3", "gap-2", "mt-2"),
    categoryLabel: clsx(
        "flex",
        "items-center",
        "gap-2",
        "text-sm",
        "text-slate-700",
        "cursor-pointer",
    ),
    errorBanner: clsx(
        "mb-4",
        "p-3",
        "bg-red-100",
        "border",
        "border-red-400",
        "text-red-700",
        "rounded",
        "text-sm",
    ),
    submittingWrapper: clsx("flex", "justify-end", "p-4"),
    submittingText: clsx("text-teal-700", "font-medium"),
};

