# Generated by Django 5.2.12 on 2026-06-27 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon_url", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "venue categories",
                "db_table": "venue_categories",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "locations",
                "indexes": [models.Index(fields=["city"], name="ix_locations_city")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                            _connector="OR",
                        ),
                        name="ck_locations_latitude",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                            _connector="OR",
                        ),
                        name="ck_locations_longitude",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField()),
                ("capacity", models.PositiveIntegerField()),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending_approval", "Pending Approval"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("amenities", models.JSONField(default=list)),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("session", "Session"),
                            ("full_day", "Full Day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="venues.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="venues.venuecategory",
                    ),
                ),
            ],
            options={
                "db_table": "venues",
            },
        ),
        migrations.CreateModel(
            name="VenueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.TextField()),
                ("is_cover", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "db_table": "venue_images",
            },
        ),
        migrations.CreateModel(
            name="VenueScheduleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_groups",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "db_table": "venue_schedule_groups",
            },
        ),
        migrations.CreateModel(
            name="VenueSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="venues.venueschedulegroup",
                    ),
                ),
            ],
            options={
                "db_table": "venue_schedules",
            },
        ),
        migrations.CreateModel(
            name="VenueScheduleGroupDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.IntegerField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="venues.venueschedulegroup",
                    ),
                ),
            ],
            options={
                "db_table": "venue_schedule_group_days",
            },
        ),
        migrations.CreateModel(
            name="VenueScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("override_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_available", models.BooleanField()),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "db_table": "venue_schedule_overrides",
            },
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["owner"], name="ix_venues_owner_id"),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["category"], name="ix_venues_category_id"),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["location"], name="ix_venues_location_id"),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["status"], name="ix_venues_status"),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["category", "status"], name="ix_venues_category_status"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["location", "status"], name="ix_venues_location_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="ck_venues_capacity_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="venueimage",
            index=models.Index(fields=["venue"], name="ix_venue_images_venue_id"),
        ),
        migrations.AddIndex(
            model_name="venueimage",
            index=models.Index(
                fields=["venue", "sort_order"], name="ix_venue_images_venue_sort"
            ),
        ),
        migrations.AddConstraint(
            model_name="venueschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="ck_schedule_time_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="venueschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="ck_schedule_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="venueschedule",
            constraint=models.UniqueConstraint(
                fields=("group", "start_time", "end_time"), name="uq_schedule_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="venueschedulegroupday",
            constraint=models.UniqueConstraint(
                fields=("group", "day_of_week"), name="uq_group_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="venueschedulegroupday",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_week__gte", 0), ("day_of_week__lte", 6)),
                name="ck_day_of_week",
            ),
        ),
        migrations.AddIndex(
            model_name="venuescheduleoverride",
            index=models.Index(fields=["venue"], name="ix_sched_override_venue"),
        ),
        migrations.AddIndex(
            model_name="venuescheduleoverride",
            index=models.Index(fields=["override_date"], name="ix_sched_override_date"),
        ),
    ]
