# Generated by Django 5.2.15 on 2026-06-30 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_seed_kerala_districts_and_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venue',
            name='unique_venue_slug',
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['slug'], name='ix_venues_slug'),
        ),
    ]
