# Generated by Django 5.2.15 on 2026-07-03 07:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0006_remove_venue_unique_venue_slug_alter_venue_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Geographic coordinates (longitude, latitude) in WGS84.",
                null=True,
                srid=4326,
            ),
        ),
    ]
