# Generated by Django 5.2.15 on 2026-07-03 07:18

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0007_add_city_location"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="city",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="ix_cities_location"
            ),
        ),
    ]
