# Generated by Django 5.2.15 on 2026-07-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0008_add_city_location_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="google_maps_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps URL for venue directions.",
                max_length=500,
                null=True,
            ),
        ),
    ]
