# Generated by Django 5.2.15 on 2026-07-18 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0012_seed_venue_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Cached average rating from reviews (0.0–5.0).",
                max_digits=2,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="review_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Cached count of reviews for this venue."
            ),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("average_rating__gte", 0), ("average_rating__lte", 5)
                ),
                name="ck_venues_average_rating_range",
            ),
        ),
    ]
