# ===================================================================
# CONFIGURATION
# ===================================================================

spring.config.import=optional:file:server/.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${DB_NAME}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
app.jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Razorpay
app.razorpay.key-id=${RAZORPAY_KEY_ID}
app.razorpay.key-secret=${RAZORPAY_KEY_SECRET}


# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Brevo
app.brevo.api-key=${BREVO_API_KEY}
app.brevo.sender-email=${BREVO_SENDER_EMAIL}
app.brevo.sender-name=${BREVO_SENDER_NAME}

