/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesIndexRouteImport } from './routes/venues.index'
import { Route as VenuesVenueIdRouteImport } from './routes/venues.$venueId'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHostIndexRouteImport } from './routes/_authenticated/host/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiStorageSplatRouteImport } from './routes/api/storage/$'
import { Route as ApiPublicVenuesRouteImport } from './routes/api/public/venues'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedHostCouponsRouteImport } from './routes/_authenticated/host/coupons'
import { Route as AuthenticatedAdminVenuesRouteImport } from './routes/_authenticated/admin.venues'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAccountBookingsRouteImport } from './routes/_authenticated/account.bookings'
import { Route as AuthenticatedHostVenuesIndexRouteImport } from './routes/_authenticated/host/venues.index'
import { Route as AuthenticatedHostBookingsIndexRouteImport } from './routes/_authenticated/host/bookings.index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as AuthenticatedHostVenuesNewRouteImport } from './routes/_authenticated/host/venues.new'
import { Route as AuthenticatedHostBookingsNewRouteImport } from './routes/_authenticated/host/bookings.new'
import { Route as AuthenticatedHostBookingsBlockOffRouteImport } from './routes/_authenticated/host/bookings.block-off'
import { Route as AuthenticatedHostVenuesVenueIdEditRouteImport } from './routes/_authenticated/host/venues.$venueId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostIndexRoute = AuthenticatedHostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHostRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiStorageSplatRoute = ApiStorageSplatRouteImport.update({
  id: '/api/storage/$',
  path: '/api/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVenuesRoute = ApiPublicVenuesRouteImport.update({
  id: '/api/public/venues',
  path: '/api/public/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostCouponsRoute =
  AuthenticatedHostCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedAdminVenuesRoute =
  AuthenticatedAdminVenuesRouteImport.update({
    id: '/venues',
    path: '/venues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountBookingsRoute =
  AuthenticatedAccountBookingsRouteImport.update({
    id: '/account/bookings',
    path: '/account/bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostVenuesIndexRoute =
  AuthenticatedHostVenuesIndexRouteImport.update({
    id: '/venues/',
    path: '/venues/',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostBookingsIndexRoute =
  AuthenticatedHostBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHostVenuesNewRoute =
  AuthenticatedHostVenuesNewRouteImport.update({
    id: '/venues/new',
    path: '/venues/new',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostBookingsNewRoute =
  AuthenticatedHostBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostBookingsBlockOffRoute =
  AuthenticatedHostBookingsBlockOffRouteImport.update({
    id: '/bookings/block-off',
    path: '/bookings/block-off',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostVenuesVenueIdEditRoute =
  AuthenticatedHostVenuesVenueIdEditRouteImport.update({
    id: '/venues/$venueId/edit',
    path: '/venues/$venueId/edit',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/api/bookings': typeof ApiBookingsRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/venues/': typeof VenuesIndexRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/venues': typeof AuthenticatedAdminVenuesRoute
  '/host/coupons': typeof AuthenticatedHostCouponsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/venues': typeof ApiPublicVenuesRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/host/': typeof AuthenticatedHostIndexRoute
  '/host/bookings/block-off': typeof AuthenticatedHostBookingsBlockOffRoute
  '/host/bookings/new': typeof AuthenticatedHostBookingsNewRoute
  '/host/venues/new': typeof AuthenticatedHostVenuesNewRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/host/bookings/': typeof AuthenticatedHostBookingsIndexRoute
  '/host/venues/': typeof AuthenticatedHostVenuesIndexRoute
  '/host/venues/$venueId/edit': typeof AuthenticatedHostVenuesVenueIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/venues': typeof VenuesIndexRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/venues': typeof AuthenticatedAdminVenuesRoute
  '/host/coupons': typeof AuthenticatedHostCouponsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/venues': typeof ApiPublicVenuesRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/host': typeof AuthenticatedHostIndexRoute
  '/host/bookings/block-off': typeof AuthenticatedHostBookingsBlockOffRoute
  '/host/bookings/new': typeof AuthenticatedHostBookingsNewRoute
  '/host/venues/new': typeof AuthenticatedHostVenuesNewRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/host/bookings': typeof AuthenticatedHostBookingsIndexRoute
  '/host/venues': typeof AuthenticatedHostVenuesIndexRoute
  '/host/venues/$venueId/edit': typeof AuthenticatedHostVenuesVenueIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/host': typeof AuthenticatedHostRouteWithChildren
  '/api/bookings': typeof ApiBookingsRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/venues/': typeof VenuesIndexRoute
  '/_authenticated/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/venues': typeof AuthenticatedAdminVenuesRoute
  '/_authenticated/host/coupons': typeof AuthenticatedHostCouponsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/venues': typeof ApiPublicVenuesRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/host/': typeof AuthenticatedHostIndexRoute
  '/_authenticated/host/bookings/block-off': typeof AuthenticatedHostBookingsBlockOffRoute
  '/_authenticated/host/bookings/new': typeof AuthenticatedHostBookingsNewRoute
  '/_authenticated/host/venues/new': typeof AuthenticatedHostVenuesNewRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/_authenticated/host/bookings/': typeof AuthenticatedHostBookingsIndexRoute
  '/_authenticated/host/venues/': typeof AuthenticatedHostVenuesIndexRoute
  '/_authenticated/host/venues/$venueId/edit': typeof AuthenticatedHostVenuesVenueIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/host'
    | '/api/bookings'
    | '/venues/$venueId'
    | '/venues/'
    | '/account/bookings'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/venues'
    | '/host/coupons'
    | '/api/auth/$'
    | '/api/public/venues'
    | '/api/storage/$'
    | '/admin/'
    | '/host/'
    | '/host/bookings/block-off'
    | '/host/bookings/new'
    | '/host/venues/new'
    | '/api/public/telegram/webhook'
    | '/host/bookings/'
    | '/host/venues/'
    | '/host/venues/$venueId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/bookings'
    | '/venues/$venueId'
    | '/venues'
    | '/account/bookings'
    | '/admin/bookings'
    | '/admin/coupons'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/venues'
    | '/host/coupons'
    | '/api/auth/$'
    | '/api/public/venues'
    | '/api/storage/$'
    | '/admin'
    | '/host'
    | '/host/bookings/block-off'
    | '/host/bookings/new'
    | '/host/venues/new'
    | '/api/public/telegram/webhook'
    | '/host/bookings'
    | '/host/venues'
    | '/host/venues/$venueId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/host'
    | '/api/bookings'
    | '/venues/$venueId'
    | '/venues/'
    | '/_authenticated/account/bookings'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/venues'
    | '/_authenticated/host/coupons'
    | '/api/auth/$'
    | '/api/public/venues'
    | '/api/storage/$'
    | '/_authenticated/admin/'
    | '/_authenticated/host/'
    | '/_authenticated/host/bookings/block-off'
    | '/_authenticated/host/bookings/new'
    | '/_authenticated/host/venues/new'
    | '/api/public/telegram/webhook'
    | '/_authenticated/host/bookings/'
    | '/_authenticated/host/venues/'
    | '/_authenticated/host/venues/$venueId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicVenuesRoute: typeof ApiPublicVenuesRoute
  ApiStorageSplatRoute: typeof ApiStorageSplatRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host/': {
      id: '/_authenticated/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof AuthenticatedHostIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/storage/$': {
      id: '/api/storage/$'
      path: '/api/storage/$'
      fullPath: '/api/storage/$'
      preLoaderRoute: typeof ApiStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/venues': {
      id: '/api/public/venues'
      path: '/api/public/venues'
      fullPath: '/api/public/venues'
      preLoaderRoute: typeof ApiPublicVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/coupons': {
      id: '/_authenticated/host/coupons'
      path: '/coupons'
      fullPath: '/host/coupons'
      preLoaderRoute: typeof AuthenticatedHostCouponsRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/admin/venues': {
      id: '/_authenticated/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AuthenticatedAdminVenuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/bookings': {
      id: '/_authenticated/account/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AuthenticatedAccountBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host/venues/': {
      id: '/_authenticated/host/venues/'
      path: '/venues'
      fullPath: '/host/venues/'
      preLoaderRoute: typeof AuthenticatedHostVenuesIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/bookings/': {
      id: '/_authenticated/host/bookings/'
      path: '/bookings'
      fullPath: '/host/bookings/'
      preLoaderRoute: typeof AuthenticatedHostBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/venues/new': {
      id: '/_authenticated/host/venues/new'
      path: '/venues/new'
      fullPath: '/host/venues/new'
      preLoaderRoute: typeof AuthenticatedHostVenuesNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/bookings/new': {
      id: '/_authenticated/host/bookings/new'
      path: '/bookings/new'
      fullPath: '/host/bookings/new'
      preLoaderRoute: typeof AuthenticatedHostBookingsNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/bookings/block-off': {
      id: '/_authenticated/host/bookings/block-off'
      path: '/bookings/block-off'
      fullPath: '/host/bookings/block-off'
      preLoaderRoute: typeof AuthenticatedHostBookingsBlockOffRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/venues/$venueId/edit': {
      id: '/_authenticated/host/venues/$venueId/edit'
      path: '/venues/$venueId/edit'
      fullPath: '/host/venues/$venueId/edit'
      preLoaderRoute: typeof AuthenticatedHostVenuesVenueIdEditRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVenuesRoute: typeof AuthenticatedAdminVenuesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVenuesRoute: AuthenticatedAdminVenuesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedHostRouteChildren {
  AuthenticatedHostCouponsRoute: typeof AuthenticatedHostCouponsRoute
  AuthenticatedHostIndexRoute: typeof AuthenticatedHostIndexRoute
  AuthenticatedHostBookingsBlockOffRoute: typeof AuthenticatedHostBookingsBlockOffRoute
  AuthenticatedHostBookingsNewRoute: typeof AuthenticatedHostBookingsNewRoute
  AuthenticatedHostVenuesNewRoute: typeof AuthenticatedHostVenuesNewRoute
  AuthenticatedHostBookingsIndexRoute: typeof AuthenticatedHostBookingsIndexRoute
  AuthenticatedHostVenuesIndexRoute: typeof AuthenticatedHostVenuesIndexRoute
  AuthenticatedHostVenuesVenueIdEditRoute: typeof AuthenticatedHostVenuesVenueIdEditRoute
}

const AuthenticatedHostRouteChildren: AuthenticatedHostRouteChildren = {
  AuthenticatedHostCouponsRoute: AuthenticatedHostCouponsRoute,
  AuthenticatedHostIndexRoute: AuthenticatedHostIndexRoute,
  AuthenticatedHostBookingsBlockOffRoute:
    AuthenticatedHostBookingsBlockOffRoute,
  AuthenticatedHostBookingsNewRoute: AuthenticatedHostBookingsNewRoute,
  AuthenticatedHostVenuesNewRoute: AuthenticatedHostVenuesNewRoute,
  AuthenticatedHostBookingsIndexRoute: AuthenticatedHostBookingsIndexRoute,
  AuthenticatedHostVenuesIndexRoute: AuthenticatedHostVenuesIndexRoute,
  AuthenticatedHostVenuesVenueIdEditRoute:
    AuthenticatedHostVenuesVenueIdEditRoute,
}

const AuthenticatedHostRouteWithChildren =
  AuthenticatedHostRoute._addFileChildren(AuthenticatedHostRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHostRoute: typeof AuthenticatedHostRouteWithChildren
  AuthenticatedAccountBookingsRoute: typeof AuthenticatedAccountBookingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHostRoute: AuthenticatedHostRouteWithChildren,
  AuthenticatedAccountBookingsRoute: AuthenticatedAccountBookingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicVenuesRoute: ApiPublicVenuesRoute,
  ApiStorageSplatRoute: ApiStorageSplatRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
