export const VenueCategory = {
    BEACH_SIDE: 'BEACH_SIDE',
    CONFERENCE_HALL: 'CONFERENCE_HALL',
    AUDITORIAM: 'AUDITORIAM',
    BANQUET_HALL: 'BANQUET_HALL',
    PARTY_HALL: 'PARTY_HALL',
    ROOFTOP: 'ROOFTOP',
    CAFE: 'CAFE',
    FARM_HOUSE: 'FARM_HOUSE',
    PALACE: 'PALACE',
    STUDIO: 'STUDIO',
    OUTDOOR_GARDEN: 'OUTDOOR_GARDEN',
    AUDITORIUM: 'AUDITORIUM',
    RESORT: 'RESORT',
    HOTEL: 'HOTEL'
}

export const Amenities = {
    WIFI: 'WIFI',
    PARKING: 'PARKING',
    AIR_CONDITIONING: 'AIR_CONDITIONING',
    CATERING_KITCHEN: 'CATERING_KITCHEN',
    SOUND_SYSTEM: 'SOUND_SYSTEM',
    PROJECTOR: 'PROJECTOR',
    STAGE: 'STAGE',
    DANCE_FLOOR: 'DANCE_FLOOR',
    OUTDOOR_AREA: 'OUTDOOR_AREA',
    VALET_PARKING: 'VALET_PARKING',
    GENERATOR_BACKUP: 'GENERATOR_BACKUP',
    CCTV_SECURITY: 'CCTV_sECURITY',
    GREEN_ROOM: 'GREEN_ROOM',
    BRIDAL_SUIT: 'BRIDAL_SUIT',
    SWIMMING_POOL: 'SWIMMING_POOL',
    ELEVATOR: 'ELEVATOR',
    BAR_COUNTER: 'BAR_COUNTER',
    PHOT_BOOTH: 'PHOTO_BOOTH'
}

export const VenueStatus = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    PENDING: 'PENDING',
    REJECTED: 'REJECTED',
    SUSPENDED: 'SUSPENDED',
    DRAFT: 'DRAFT',
}