# Generated by Django 6.0.6 on 2026-07-04 21:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('engagement', 'Engagement'), ('reception', 'Reception'), ('conference', 'Conference'), ('other', 'Other')], max_length=20)),
                ('guest_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['venue', 'event_date', 'status'], name='booking_venue_date_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('guest_count__gte', 1)), name='booking_guest_count_at_least_one')],
            },
        ),
    ]
