# Generated by Django 6.0.6 on 2026-06-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookingTime', models.DateTimeField()),
                ('user_uid', models.CharField(max_length=255)),
                ('owner_uid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venueID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_uid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmv.bookings')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmv.venues'),
        ),
    ]
