# Generated by Django 6.0.6 on 2026-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='venues',
            name='owner',
        ),
        migrations.AddField(
            model_name='bookings',
            name='owner_uid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_uid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venues',
            name='owner_uid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
