"""add venue fields

Revision ID: 136fe88b327a
Revises: 
Create Date: 2026-06-12 14:27:25.878941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136fe88b327a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('venue_price', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('venue_availabilty', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('is_available', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'is_available')
    op.drop_column('venues', 'venue_availabilty')
    op.drop_column('venues', 'venue_price')
    # ### end Alembic commands ###
