"""add indexes on venue status and type

Revision ID: 1d35a50953f8
Revises: ace4f6eabba8
Create Date: 2026-06-28 22:54:49.213742
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d35a50953f8'
down_revision: Union[str, None] = 'ace4f6eabba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_venues_status'), 'venues', ['status'], unique=False)
    op.create_index(op.f('ix_venues_type'), 'venues', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_type'), table_name='venues')
    op.drop_index(op.f('ix_venues_status'), table_name='venues')
    # ### end Alembic commands ###
