import { db } from '../../db/index.js';
import { venuesTable } from '../../models/venueModel.js';
import { usersTable } from '../../models/userModel.js';
import { eq } from 'drizzle-orm';

export const seedVenues = async () => {
  console.log('Seeding venues...');
  
  // Get the actual user IDs from the database
  const johnOwner = await db
    .select({ id: usersTable.id })
    .from(usersTable)
    .where(eq(usersTable.username, 'john_owner'))
    .limit(1);
  
  const janeOwner = await db
    .select({ id: usersTable.id })
    .from(usersTable)
    .where(eq(usersTable.username, 'jane_owner'))
    .limit(1);

  if (!johnOwner[0] || !janeOwner[0]) {
    throw new Error('Users not found. Please seed users first.');
  }

  const venuesData = [
    {
      id: '550e8400-e29b-41d4-a716-446655440010',
      ownerId: johnOwner[0].id,
      name: 'Grand Ballroom',
      description: 'Elegant ballroom perfect for weddings and corporate events',
      type: 'banquet_hall',
      address: '123 Main Street, Downtown',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      latitude: '19.0760',
      longitude: '72.8777',
      capacity: 500,
      images: [
        { url: 'https://example.com/ballroom1.jpg', alt: 'Main hall' },
        { url: 'https://example.com/ballroom2.jpg', alt: 'Decorated hall' },
      ],
      openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      openTime: '10:00',
      closeTime: '23:00',
      minBookingHours: 4,
      isActive: true,
      approvalStatus: 'approved',
      adminNote: null,
      bookingType: 'daily',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440011',
      ownerId: janeOwner[0].id,
      name: 'Tech Hub Meeting Rooms',
      description: 'Modern meeting spaces with latest technology',
      type: 'meeting_room',
      address: '456 Tech Park, Bandra',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      latitude: '19.0596',
      longitude: '72.8295',
      capacity: 50,
      images: [
        { url: 'https://example.com/office1.jpg', alt: 'Meeting room' },
        { url: 'https://example.com/office2.jpg', alt: 'Conference setup' },
      ],
      openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      openTime: '09:00',
      closeTime: '18:00',
      minBookingHours: 1,
      isActive: true,
      approvalStatus: 'approved',
      adminNote: null,
      bookingType: 'hourly',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440012',
      ownerId: johnOwner[0].id,
      name: 'Garden Bistro',
      description: 'Outdoor garden venue perfect for intimate gatherings',
      type: 'outdoor_space',
      address: '789 Garden Lane, Andheri',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400072',
      latitude: '19.1136',
      longitude: '72.8697',
      capacity: 100,
      images: [
        { url: 'https://example.com/garden1.jpg', alt: 'Garden setup' },
      ],
      openDays: ['Thursday', 'Friday', 'Saturday', 'Sunday'],
      openTime: '17:00',
      closeTime: '23:00',
      minBookingHours: 3,
      isActive: true,
      approvalStatus: 'approved',
      adminNote: null,
      bookingType: 'daily',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440013',
      ownerId: janeOwner[0].id,
      name: 'Cozy Workspace',
      description: 'Quiet desk spaces with high-speed internet and coffee',
      type: 'coworking_space',
      address: '12 Rose Avenue, Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      latitude: '18.5362',
      longitude: '73.8930',
      capacity: 20,
      images: [
        { url: 'https://example.com/cowork1.jpg', alt: 'Workspace area' },
      ],
      openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      openTime: '08:00',
      closeTime: '20:00',
      minBookingHours: 1,
      isActive: true,
      approvalStatus: 'approved',
      adminNote: null,
      bookingType: 'hourly',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440014',
      ownerId: johnOwner[0].id,
      name: 'Penthouse Suite',
      description: 'Luxury rooftop suite with stunning city skyline views',
      type: 'party_lounge',
      address: '99 Sky Tower, MG Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560001',
      latitude: '12.9716',
      longitude: '77.5946',
      capacity: 75,
      images: [
        { url: 'https://example.com/penthouse.jpg', alt: 'Rooftop view' },
      ],
      openDays: ['Friday', 'Saturday', 'Sunday'],
      openTime: '16:00',
      closeTime: '02:00',
      minBookingHours: 5,
      isActive: true,
      approvalStatus: 'pending',
      adminNote: 'Requires noise level check',
      bookingType: 'daily',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440015',
      ownerId: janeOwner[0].id,
      name: 'Rusty Shed',
      description: 'Old industrial shed suited for grungy photography shoots',
      type: 'studio',
      address: '7 Outer Ring Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600001',
      latitude: '13.0827',
      longitude: '80.2707',
      capacity: 30,
      images: [
        { url: 'https://example.com/shed.jpg', alt: 'Industrial shed' },
      ],
      openDays: ['Saturday', 'Sunday'],
      openTime: '10:00',
      closeTime: '18:00',
      minBookingHours: 2,
      isActive: false,
      approvalStatus: 'rejected',
      adminNote: 'Failed safety inspection due to structural issues',
      bookingType: 'hourly',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440016',
      ownerId: johnOwner[0].id,
      name: 'Lakeside Pavilion',
      description: 'Scenic pavilion by the lake, ideal for evening parties and receptions',
      type: 'outdoor_space',
      address: '22 Lake View Road',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411042',
      latitude: '18.5150',
      longitude: '73.8562',
      capacity: 250,
      images: [
        { url: 'https://example.com/lakeside1.jpg', alt: 'Pavilion by the lake' },
      ],
      openDays: ['Thursday', 'Friday', 'Saturday', 'Sunday'],
      openTime: '16:00',
      closeTime: '01:00',
      minBookingHours: 4,
      isActive: true,
      approvalStatus: 'pending',
      adminNote: 'Pending review of parking arrangements',
      bookingType: 'daily',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440017',
      ownerId: janeOwner[0].id,
      name: 'Urban Art Loft',
      description: 'Creative loft space designed for gallery openings and workshops',
      type: 'event_space',
      address: '101 Creative Street',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560034',
      latitude: '12.9718',
      longitude: '77.6413',
      capacity: 120,
      images: [
        { url: 'https://example.com/loft.jpg', alt: 'Art loft interior' },
      ],
      openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      openTime: '10:00',
      closeTime: '22:00',
      minBookingHours: 2,
      isActive: true,
      approvalStatus: 'approved',
      adminNote: null,
      bookingType: 'hourly',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440018',
      ownerId: johnOwner[0].id,
      name: 'Heritage Courtyard',
      description: 'Historic courtyard venue with classic architecture and charm',
      type: 'heritage_property',
      address: '88 Heritage Lane',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302001',
      latitude: '26.9124',
      longitude: '75.7873',
      capacity: 180,
      images: [
        { url: 'https://example.com/courtyard.jpg', alt: 'Courtyard view' },
      ],
      openDays: ['Friday', 'Saturday', 'Sunday'],
      openTime: '14:00',
      closeTime: '23:00',
      minBookingHours: 4,
      isActive: true,
      approvalStatus: 'rejected',
      adminNote: 'No fire safety certificate on file',
      bookingType: 'daily',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440019',
      ownerId: janeOwner[0].id,
      name: 'Sunrise Conference Center',
      description: 'Large conference center with multiple halls and breakout rooms',
      type: 'conference_center',
      address: '77 Business Park',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500032',
      latitude: '17.3850',
      longitude: '78.4867',
      capacity: 400,
      images: [
        { url: 'https://example.com/conference.jpg', alt: 'Conference hall' },
      ],
      openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      openTime: '08:00',
      closeTime: '20:00',
      minBookingHours: 3,
      isActive: false,
      approvalStatus: 'approved',
      adminNote: 'Temporarily inactive for renovation',
      bookingType: 'daily',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440020',
      ownerId: johnOwner[0].id,
      name: 'Beachside Banquet',
      description: 'Open-air banquet venue right by the beach',
      type: 'banquet_hall',
      address: '12 Shoreline Road',
      city: 'Goa',
      state: 'Goa',
      pincode: '403001',
      latitude: '15.4968',
      longitude: '73.8278',
      capacity: 300,
      images: [
        { url: 'https://example.com/beachbanquet.jpg', alt: 'Beachside banquet' },
      ],
      openDays: ['Friday', 'Saturday', 'Sunday'],
      openTime: '15:00',
      closeTime: '01:00',
      minBookingHours: 5,
      isActive: true,
      approvalStatus: 'pending',
      adminNote: 'Pending review of flood safety measures',
      bookingType: 'daily',
    },
  ];

  await db.insert(venuesTable).values(venuesData).onConflictDoNothing();
  console.log('✓ Venues done');
};
