// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewSlot = `-- name: CreateNewSlot :one
INSERT INTO availability (venue_id, start_time, end_time)
VALUES ($1, $2, $3)
RETURNING id, venue_id, start_time, end_time
`

type CreateNewSlotParams struct {
	VenueID   pgtype.UUID      `json:"venue_id"`
	StartTime pgtype.Timestamp `json:"start_time"`
	EndTime   pgtype.Timestamp `json:"end_time"`
}

func (q *Queries) CreateNewSlot(ctx context.Context, arg CreateNewSlotParams) (Availability, error) {
	row := q.db.QueryRow(ctx, createNewSlot, arg.VenueID, arg.StartTime, arg.EndTime)
	var i Availability
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteSlot = `-- name: DeleteSlot :exec
DELETE FROM availability
WHERE id = $1
`

func (q *Queries) DeleteSlot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSlot, id)
	return err
}

const getAvailableSlotsByVenueID = `-- name: GetAvailableSlotsByVenueID :many
SELECT id, venue_id, start_time, end_time FROM availability
WHERE venue_id = $1
`

func (q *Queries) GetAvailableSlotsByVenueID(ctx context.Context, venueID pgtype.UUID) ([]Availability, error) {
	rows, err := q.db.Query(ctx, getAvailableSlotsByVenueID, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
