// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, venue_id, slot_id, total_amount, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, venue_id, slot_id, status, total_amount, created_at, updated_at
`

type CreateBookingParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	VenueID     pgtype.UUID    `json:"venue_id"`
	SlotID      pgtype.UUID    `json:"slot_id"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.VenueID,
		arg.SlotID,
		arg.TotalAmount,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.SlotID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, user_id, venue_id, slot_id, status, total_amount, created_at, updated_at FROM bookings
WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.SlotID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingsByUserID = `-- name: GetBookingsByUserID :many
SELECT id, user_id, venue_id, slot_id, status, total_amount, created_at, updated_at FROM bookings
WHERE user_id = $1 AND status = 'confirmed'
ORDER BY created_at DESC
`

func (q *Queries) GetBookingsByUserID(ctx context.Context, userID pgtype.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VenueID,
			&i.SlotID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlotByBookingID = `-- name: GetSlotByBookingID :one
SELECT slot_id FROM bookings
WHERE id = $1
`

func (q *Queries) GetSlotByBookingID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSlotByBookingID, id)
	var slot_id pgtype.UUID
	err := row.Scan(&slot_id)
	return slot_id, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings
SET status = $2
WHERE id = $1
`

type UpdateBookingStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.Exec(ctx, updateBookingStatus, arg.ID, arg.Status)
	return err
}
