// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVenueImage = `-- name: AddVenueImage :one
INSERT INTO venue_images (venue_id, image_url)
VALUES ($1, $2)
RETURNING id, venue_id, image_url
`

type AddVenueImageParams struct {
	VenueID  pgtype.UUID `json:"venue_id"`
	ImageUrl string      `json:"image_url"`
}

func (q *Queries) AddVenueImage(ctx context.Context, arg AddVenueImageParams) (VenueImage, error) {
	row := q.db.QueryRow(ctx, addVenueImage, arg.VenueID, arg.ImageUrl)
	var i VenueImage
	err := row.Scan(&i.ID, &i.VenueID, &i.ImageUrl)
	return i, err
}

const assignAmenityToVenue = `-- name: AssignAmenityToVenue :exec
INSERT INTO venue_amenities (venue_id, amenity_id)
VALUES ($1, $2)
`

type AssignAmenityToVenueParams struct {
	VenueID   pgtype.UUID `json:"venue_id"`
	AmenityID pgtype.UUID `json:"amenity_id"`
}

func (q *Queries) AssignAmenityToVenue(ctx context.Context, arg AssignAmenityToVenueParams) error {
	_, err := q.db.Exec(ctx, assignAmenityToVenue, arg.VenueID, arg.AmenityID)
	return err
}

const createAmenity = `-- name: CreateAmenity :one
INSERT INTO amenities (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateAmenity(ctx context.Context, name string) (Amenity, error) {
	row := q.db.QueryRow(ctx, createAmenity, name)
	var i Amenity
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    owner_id,
    name,
    description,
    category,
    address,
    city,
    state,
    pincode,
    capacity,
    price_per_hour,
    price_per_day
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, owner_id, name, description, category, address, city, state, pincode, capacity, price_per_hour, price_per_day, status, created_at, updated_at
`

type CreateVenueParams struct {
	OwnerID      pgtype.UUID    `json:"owner_id"`
	Name         string         `json:"name"`
	Description  *string        `json:"description"`
	Category     string         `json:"category"`
	Address      string         `json:"address"`
	City         string         `json:"city"`
	State        string         `json:"state"`
	Pincode      *string        `json:"pincode"`
	Capacity     *int32         `json:"capacity"`
	PricePerHour pgtype.Numeric `json:"price_per_hour"`
	PricePerDay  pgtype.Numeric `json:"price_per_day"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Address,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.Capacity,
		arg.PricePerHour,
		arg.PricePerDay,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Capacity,
		&i.PricePerHour,
		&i.PricePerDay,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues
WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVenue, id)
	return err
}

const deleteVenueImage = `-- name: DeleteVenueImage :exec
DELETE FROM venue_images
WHERE id = $1
`

func (q *Queries) DeleteVenueImage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVenueImage, id)
	return err
}

const findVenuesByCategory = `-- name: FindVenuesByCategory :many
SELECT id, owner_id, name, description, category, address, city, state, pincode, capacity, price_per_hour, price_per_day, status, created_at, updated_at FROM venues
WHERE category = $1 AND status = 'approved'
`

func (q *Queries) FindVenuesByCategory(ctx context.Context, category string) ([]Venue, error) {
	rows, err := q.db.Query(ctx, findVenuesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Address,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.Capacity,
			&i.PricePerHour,
			&i.PricePerDay,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findVenuesByPriceRange = `-- name: FindVenuesByPriceRange :many
SELECT id, owner_id, name, description, category, address, city, state, pincode, capacity, price_per_hour, price_per_day, status, created_at, updated_at FROM venues
WHERE price_per_hour BETWEEN $1 AND $2
AND status = 'approved'
`

type FindVenuesByPriceRangeParams struct {
	PricePerHour   pgtype.Numeric `json:"price_per_hour"`
	PricePerHour_2 pgtype.Numeric `json:"price_per_hour_2"`
}

func (q *Queries) FindVenuesByPriceRange(ctx context.Context, arg FindVenuesByPriceRangeParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, findVenuesByPriceRange, arg.PricePerHour, arg.PricePerHour_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Address,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.Capacity,
			&i.PricePerHour,
			&i.PricePerDay,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findVenuesInACity = `-- name: FindVenuesInACity :many
SELECT id, owner_id, name, description, category, address, city, state, pincode, capacity, price_per_hour, price_per_day, status, created_at, updated_at FROM venues
WHERE city = $1 AND status = 'approved'
`

func (q *Queries) FindVenuesInACity(ctx context.Context, city string) ([]Venue, error) {
	rows, err := q.db.Query(ctx, findVenuesInACity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Address,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.Capacity,
			&i.PricePerHour,
			&i.PricePerDay,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAmenities = `-- name: GetAllAmenities :many
SELECT id, name FROM amenities
ORDER BY name
`

func (q *Queries) GetAllAmenities(ctx context.Context) ([]Amenity, error) {
	rows, err := q.db.Query(ctx, getAllAmenities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amenity
	for rows.Next() {
		var i Amenity
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVenues = `-- name: GetAllVenues :many
SELECT id, owner_id, name, description, category, address, city, state, pincode, capacity, price_per_hour, price_per_day, status, created_at, updated_at FROM venues
WHERE status = 'approved'
ORDER BY created_at DESC
`

func (q *Queries) GetAllVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.Query(ctx, getAllVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Address,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.Capacity,
			&i.PricePerHour,
			&i.PricePerDay,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAmenitiesForVenue = `-- name: GetAmenitiesForVenue :many
SELECT a.id, a.name
FROM venue_amenities va
JOIN amenities a
ON a.id = va.amenity_id
WHERE va.venue_id = $1
`

func (q *Queries) GetAmenitiesForVenue(ctx context.Context, venueID pgtype.UUID) ([]Amenity, error) {
	rows, err := q.db.Query(ctx, getAmenitiesForVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amenity
	for rows.Next() {
		var i Amenity
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, owner_id, name, description, category, address, city, state, pincode, capacity, price_per_hour, price_per_day, status, created_at, updated_at FROM venues
WHERE id = $1
`

func (q *Queries) GetVenueByID(ctx context.Context, id pgtype.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Capacity,
		&i.PricePerHour,
		&i.PricePerDay,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenueImages = `-- name: GetVenueImages :many
SELECT id, venue_id, image_url FROM venue_images
WHERE venue_id = $1
`

func (q *Queries) GetVenueImages(ctx context.Context, venueID pgtype.UUID) ([]VenueImage, error) {
	rows, err := q.db.Query(ctx, getVenueImages, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VenueImage
	for rows.Next() {
		var i VenueImage
		if err := rows.Scan(&i.ID, &i.VenueID, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVenuesByOwnerID = `-- name: GetVenuesByOwnerID :many
SELECT id, owner_id, name, description, category, address, city, state, pincode, capacity, price_per_hour, price_per_day, status, created_at, updated_at FROM venues
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetVenuesByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Venue, error) {
	rows, err := q.db.Query(ctx, getVenuesByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Address,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.Capacity,
			&i.PricePerHour,
			&i.PricePerDay,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAmenityFromVenue = `-- name: RemoveAmenityFromVenue :exec
DELETE FROM venue_amenities
WHERE venue_id = $1 AND amenity_id = $2
`

type RemoveAmenityFromVenueParams struct {
	VenueID   pgtype.UUID `json:"venue_id"`
	AmenityID pgtype.UUID `json:"amenity_id"`
}

func (q *Queries) RemoveAmenityFromVenue(ctx context.Context, arg RemoveAmenityFromVenueParams) error {
	_, err := q.db.Exec(ctx, removeAmenityFromVenue, arg.VenueID, arg.AmenityID)
	return err
}
