"""Add guest_count and phone to lead_reservations

Revision ID: 0b15a59e8154
Revises: c00a79140491
Create Date: 2026-07-06 13:35:36.380854

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0b15a59e8154'
down_revision: Union[str, None] = 'c00a79140491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_reservations', sa.Column('guest_count', sa.Integer(), nullable=True))
    op.add_column('lead_reservations', sa.Column('phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_reservations', 'phone')
    op.drop_column('lead_reservations', 'guest_count')
    # ### end Alembic commands ###
