"""deep research search query table

Revision ID: 5134b9fb1f9e
Revises: 85bed236d64b
Create Date: 2026-07-05 13:41:00.515010

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5134b9fb1f9e'
down_revision: Union[str, None] = '85bed236d64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_research_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('city_filter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deep_research_queries')
    # ### end Alembic commands ###
