"""deep research admin required fields

Revision ID: 75699ec24359
Revises: 511aedccb502
Create Date: 2026-07-07 17:23:56.774694

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75699ec24359'
down_revision: Union[str, None] = '511aedccb502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_reservations', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('lead_reservations', sa.Column('venue_id', sa.UUID(), nullable=True))
    op.add_column('lead_reservations', sa.Column('booking_id', sa.UUID(), nullable=True))
    op.add_column('lead_reservations', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('lead_reservations', sa.Column('contact_notes', sa.Text(), nullable=True))
    op.add_column('lead_reservations', sa.Column('follow_up_date', sa.Date(), nullable=True))
    op.add_column('lead_reservations', sa.Column('contact_method', sa.Text(), nullable=True))
    op.add_column('lead_reservations', sa.Column('owner_invited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lead_reservations', sa.Column('booking_created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_lead_reservations_venue_id', 'lead_reservations', ['venue_id'], unique=False, postgresql_where=sa.text('venue_id IS NOT NULL'))
    op.create_foreign_key(None, 'lead_reservations', 'venues', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'lead_reservations', 'venue_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'lead_reservations', 'profiles', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'lead_reservations', 'bookings', ['booking_id'], ['id'])
    op.alter_column('venues', 'booking_mode',
               existing_type=postgresql.ENUM('MANUAL', 'INSTANT', name='booking_mode'),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'booking_mode',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('MANUAL', 'INSTANT', name='booking_mode'),
               existing_nullable=False)
    op.drop_constraint(None, 'lead_reservations', type_='foreignkey')
    op.drop_constraint(None, 'lead_reservations', type_='foreignkey')
    op.drop_constraint(None, 'lead_reservations', type_='foreignkey')
    op.drop_constraint(None, 'lead_reservations', type_='foreignkey')
    op.drop_index('ix_lead_reservations_venue_id', table_name='lead_reservations', postgresql_where=sa.text('venue_id IS NOT NULL'))
    op.drop_column('lead_reservations', 'booking_created_at')
    op.drop_column('lead_reservations', 'owner_invited_at')
    op.drop_column('lead_reservations', 'contact_method')
    op.drop_column('lead_reservations', 'follow_up_date')
    op.drop_column('lead_reservations', 'contact_notes')
    op.drop_column('lead_reservations', 'category_id')
    op.drop_column('lead_reservations', 'booking_id')
    op.drop_column('lead_reservations', 'venue_id')
    op.drop_column('lead_reservations', 'owner_id')
    # ### end Alembic commands ###
