"""dynamic pricing model change

Revision ID: 85bed236d64b
Revises: 4375235671ba
Create Date: 2026-07-03 01:18:26.521190

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '85bed236d64b'
down_revision: Union[str, None] = '4375235671ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('adjustment_type', sa.Text(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('applies_to', sa.Text(), server_default=sa.text("'both'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'owner'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(adjustment_type = 'multiplier' AND multiplier IS NOT NULL AND multiplier > 0 AND amount_paise IS NULL) OR (adjustment_type = 'fixed_delta' AND amount_paise IS NOT NULL AND multiplier IS NULL) OR (adjustment_type = 'override' AND amount_paise IS NOT NULL AND amount_paise >= 0 AND multiplier IS NULL)", name='ck_venue_pricing_rules_adjustment_payload'),
    sa.CheckConstraint("adjustment_type IN ('multiplier', 'fixed_delta', 'override')", name='ck_venue_pricing_rules_adjustment_type'),
    sa.CheckConstraint("applies_to IN ('full_day', 'time_slot', 'both')", name='ck_venue_pricing_rules_applies_to'),
    sa.CheckConstraint("source IN ('owner', 'system')", name='ck_venue_pricing_rules_source'),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date', name='ck_venue_pricing_rules_date_range'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_venue_pricing_rules_priority', 'venue_pricing_rules', ['venue_id', 'priority'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.add_column('bookings', sa.Column('pricing_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('venues', sa.Column('min_price_pct', sa.Numeric(precision=5, scale=2), server_default='50.00', nullable=False))
    op.add_column('venues', sa.Column('max_price_pct', sa.Numeric(precision=5, scale=2), server_default='200.00', nullable=False))
    op.add_column('venues', sa.Column('display_price_min_paise', sa.BigInteger(), nullable=True))
    op.add_column('venues', sa.Column('display_price_max_paise', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'display_price_max_paise')
    op.drop_column('venues', 'display_price_min_paise')
    op.drop_column('venues', 'max_price_pct')
    op.drop_column('venues', 'min_price_pct')
    op.drop_column('bookings', 'pricing_breakdown')
    op.drop_index('idx_venue_pricing_rules_priority', table_name='venue_pricing_rules', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_table('venue_pricing_rules')
    # ### end Alembic commands ###
