"""add_deep_research_phase_2

Revision ID: 9530e5e46835
Revises: 5134b9fb1f9e
Create Date: 2026-07-05 19:15:09.813040

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9530e5e46835'
down_revision: Union[str, None] = '5134b9fb1f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_discovery_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['deep_research_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    op.create_table('external_venue_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discovered_via_query_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('category_guess', sa.Text(), nullable=True),
    sa.Column('raw_contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'CONTACTED', 'ONBOARDED', 'REJECTED', name='external_lead_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discovered_via_query_id'], ['deep_research_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_venue_leads_source_ref'), 'external_venue_leads', ['source_ref'], unique=False)

    op.create_table('lead_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ADMIN_CONTACTED', 'OWNER_CONFIRMED', 'DECLINED', 'EXPIRED', name='lead_reservation_status'), nullable=False),
    sa.Column('platform_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['external_venue_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_reservations')
    op.drop_index(op.f('ix_external_venue_leads_source_ref'), table_name='external_venue_leads')
    op.drop_table('external_venue_leads')
    op.drop_table('external_discovery_requests')
    
    op.execute("DROP TYPE IF EXISTS external_lead_status")
    op.execute("DROP TYPE IF EXISTS lead_reservation_status")
    # ### end Alembic commands ###
