"""add_new_fields_bookings

Revision ID: ab7cfebcbee6
Revises: c4854b7f080d
Create Date: 2026-07-05 15:37:01.613230

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ab7cfebcbee6'
down_revision: Union[str, None] = 'c4854b7f080d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('auto_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('confirmed_by', sa.Text(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'confirmed_by')
    op.drop_column('bookings', 'auto_confirmed_at')
    op.drop_column('bookings', 'payment_expires_at')
    # ### end Alembic commands ###
