"""add_notifications_composite_index

Revision ID: c6e1d278636c
Revises: 71e611d6dd24
Create Date: 2026-07-18 10:02:34.696545

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c6e1d278636c'
down_revision: Union[str, None] = '71e611d6dd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_user_id_created_at', table_name='notifications')
    # ### end Alembic commands ###
