"""deep research logs field update

Revision ID: c7ff94364ee8
Revises: 9530e5e46835
Create Date: 2026-07-06 00:41:16.979095

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c7ff94364ee8'
down_revision: Union[str, None] = '9530e5e46835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('bookings', 'confirmed_by')
    op.drop_column('bookings', 'payment_expires_at')
    op.drop_column('bookings', 'auto_confirmed_at')
    op.add_column('deep_research_queries', sa.Column('understanding_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('deep_research_queries', sa.Column('result_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('deep_research_queries', sa.Column('avg_match_score', sa.Float(), nullable=True))
    op.add_column('deep_research_queries', sa.Column('top_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('venues', 'booking_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('booking_mode', postgresql.ENUM('MANUAL', 'INSTANT', name='booking_mode'), autoincrement=False, nullable=False))
    op.drop_column('deep_research_queries', 'top_results_json')
    op.drop_column('deep_research_queries', 'avg_match_score')
    op.drop_column('deep_research_queries', 'result_count')
    op.drop_column('deep_research_queries', 'understanding_json')
    op.add_column('bookings', sa.Column('auto_confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('payment_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('confirmed_by', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('slots')
    # ### end Alembic commands ###
