"""deep research logs field update

Revision ID: c7ff94364ee8
Revises: 9530e5e46835
Create Date: 2026-07-06 00:41:16.979095

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c7ff94364ee8'
down_revision: Union[str, None] = '9530e5e46835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('deep_research_queries', sa.Column('understanding_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('deep_research_queries', sa.Column('result_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('deep_research_queries', sa.Column('avg_match_score', sa.Float(), nullable=True))
    op.add_column('deep_research_queries', sa.Column('top_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deep_research_queries', 'top_results_json')
    op.drop_column('deep_research_queries', 'avg_match_score')
    op.drop_column('deep_research_queries', 'result_count')
    op.drop_column('deep_research_queries', 'understanding_json')
    # ### end Alembic commands ###
