"""add_ratings_venue_table

Revision ID: dfe745817ac5
Revises: da3960835584
Create Date: 2026-07-09 03:23:39.382732

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dfe745817ac5'
down_revision: Union[str, None] = 'da3960835584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('hidden_reason', sa.String(length=255), nullable=True),
    sa.Column('hidden_by', sa.UUID(), nullable=True),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hidden_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_venue_reviews_created_at'), 'venue_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_venue_reviews_deleted_at'), 'venue_reviews', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_venue_reviews_is_hidden'), 'venue_reviews', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_venue_reviews_user_id'), 'venue_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_venue_reviews_venue_id'), 'venue_reviews', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_reviews_venue_id'), table_name='venue_reviews')
    op.drop_index(op.f('ix_venue_reviews_user_id'), table_name='venue_reviews')
    op.drop_index(op.f('ix_venue_reviews_is_hidden'), table_name='venue_reviews')
    op.drop_index(op.f('ix_venue_reviews_deleted_at'), table_name='venue_reviews')
    op.drop_index(op.f('ix_venue_reviews_created_at'), table_name='venue_reviews')
    op.drop_table('venue_reviews')
    # ### end Alembic commands ###
