export const ROUTE_PATHS = {
  USER: {
    BASE: 'user',
    LOGIN: 'login',
    SIGNUP: 'register',
    FORGOT_PASSWORD: 'forgot-password',
    RESET_PASSWORD: 'reset-password',
    DASHBOARD: 'dashboard',
    VENUES: 'venues',
    VENUE_DETAILS: 'venues/:id',
    CHECKOUT: 'checkout/:venueId',
    MY_BOOKINGS: 'my-bookings',
    MY_BOOKING_DETAIL: 'my-bookings/:id',
    PROFILE: 'profile',
  },
  VENDOR: {
    BASE: 'vendor',
    LOGIN: 'login',
    SIGNUP: 'register',
    FORGOT_PASSWORD: 'forgot-password',
    DASHBOARD: 'dashboard',
    VENUES: 'venues',
    CREATE_VENUE: 'venues/create',
    EDIT_VENUE: 'venues/:id/edit',
    BOOKINGS: 'bookings',
    ANALYTICS: 'analytics',
    SETTINGS: 'settings',
    VENUE_SLOTS: 'venues/:id/slots',
  },
  ADMIN: {
    BASE: 'admin',
    LOGIN: 'login',
    FORGOT_PASSWORD: 'forgot-password',
    DASHBOARD: 'dashboard',
    USERS: 'users',
    VENDORS: 'vendors',
    VENUES: 'venues',
    BOOKINGS: 'bookings',
    ANALYTICS: 'analytics',
    SETTINGS: 'settings',
  },
} as const;
