"""add owner dashboard support

Revision ID: 578c5c4483ac
Revises: 5ac4f1561c21
Create Date: 2026-06-30 16:08:20.714621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578c5c4483ac'
down_revision: Union[str, None] = '5ac4f1561c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('event_type', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('guest_count', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('owner_status', sa.String(length=20), nullable=False))
    op.add_column('venues', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_url')
    op.drop_column('venues', 'capacity')
    op.drop_column('bookings', 'owner_status')
    op.drop_column('bookings', 'guest_count')
    op.drop_column('bookings', 'event_type')
    # ### end Alembic commands ###
