import clsx from "clsx";

export const addVenueStyle = {
    pageWrapper: clsx(
        "ml-6",
        "mt-2",
    ),
    formBox: clsx(
        "grid",
        "gap-6",
        "lg:grid-cols-[1.2fr_1fr]",
    ),
    basicInfoCard: clsx(
        "rounded-3xl",
        "border",
        "border-slate-200",
        "bg-white",
        "p-6",
        "shadow-sm",
        "lg:p-8",
    ),
    card: clsx(
        "rounded-3xl",
        "border",
        "border-slate-200",
        "bg-white",
        "p-6",
        "shadow-sm",
        "lg:p-8",
    ),
    headerWrapper: clsx(
        "mb-6",
        "flex",
        "items-center",
        "gap-3",
    ),
    headerIcon: clsx(
        "h-6",
        "w-6",
        "text-teal-600",
    ),
    headerTitle: clsx(
        "text-lg",
        "font-semibold",
        "text-slate-900",
    ),
    fieldGrid: clsx(
        "grid",
        "gap-6",
        "md:grid-cols-2",
    ),
    rowGrid3: clsx(
        "grid",
        "gap-4",
        "md:grid-cols-3",
    ),
    rowGrid2: clsx(
        "grid",
        "gap-4",
        "md:grid-cols-2",
    ),
    rowWrapper: clsx(
        "mt-4",
    ),
    label: clsx(
        "mb-2",
        "block",
        "text-sm",
        "font-medium",
        "text-slate-700",
    ),
    input: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "px-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
        "sm:h-14",
    ),
    select: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "px-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
        "sm:h-14",
    ),
    textarea: clsx(
        "w-full",
        "resize-none",
        "rounded-xl",
        "border",
        "border-slate-200",
        "p-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
    ),
    descriptionWrapper: clsx(
        "mt-6",
    ),
    charCounter: clsx(
        "mt-2",
        "text-right",
        "text-xs",
        "text-slate-400",
    ),
    amenitiesGrid: clsx(
        "grid",
        "gap-y-4",
        "gap-x-6",
        "sm:grid-cols-2",
        "lg:grid-cols-3",
    ),
    checkboxLabel: clsx(
        "flex",
        "cursor-pointer",
        "items-center",
        "gap-3",
        "text-sm",
        "text-slate-700",
    ),
    checkbox: clsx(
        "h-4",
        "w-4",
        "rounded",
        "border-slate-300",
        "text-teal-600",
        "focus:ring-teal-500",
    ),
    buttonSecondary: clsx(
        "mt-5",
        "inline-flex",
        "items-center",
        "gap-2",
        "rounded-xl",
        "border",
        "border-teal-200",
        "bg-white",
        "px-5",
        "py-3",
        "text-sm",
        "font-medium",
        "text-teal-700",
        "transition",
        "hover:bg-teal-50",
    ),
    uploadZone: clsx(
        "flex",
        "h-28",
        "cursor-pointer",
        "flex-col",
        "items-center",
        "justify-center",
        "rounded-2xl",
        "border-2",
        "border-dashed",
        "border-slate-300",
        "transition",
        "hover:border-teal-500",
        "hover:bg-teal-50/30",
    ),
    uploadIcon: clsx(
        "mb-2",
        "h-7",
        "w-7",
        "text-teal-600",
    ),
    uploadText: clsx(
        "text-sm",
        "font-medium",
        "text-slate-900",
    ),
    uploadSubtext: clsx(
        "mt-1",
        "text-xs",
        "text-slate-500",
    ),
    galleryLabel: clsx(
        "mb-3",
        "text-sm",
        "font-medium",
        "text-slate-700",
    ),
    galleryGrid: clsx(
        "grid",
        "grid-cols-3",
        "gap-3",
        "sm:grid-cols-5",
    ),
    galleryAddButton: clsx(
        "flex",
        "h-16",
        "w-full",
        "items-center",
        "justify-center",
        "rounded-xl",
        "border-2",
        "border-dashed",
        "border-slate-300",
        "transition",
        "hover:border-teal-500",
        "hover:bg-teal-50/30",
    ),
    galleryAddIcon: clsx(
        "h-5",
        "w-5",
        "text-slate-500",
    ),
    headerSubtitle: clsx(
        "mt-1",
        "text-sm",
        "text-slate-500",
    ),
    searchWrapper: clsx(
        "relative",
        "mb-4",
    ),
    searchIcon: clsx(
        "absolute",
        "left-3",
        "top-1/2",
        "h-4",
        "w-4",
        "-translate-y-1/2",
        "text-slate-400",
    ),
    searchInput: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "pl-10",
        "pr-4",
        "text-sm",
        "outline-none",
        "transition",
        "focus:border-teal-600",
        "focus:ring-2",
        "focus:ring-teal-100",
        "sm:h-14",
    ),
    mapBox: clsx(
        "h-[320px]",
        "overflow-hidden",
        "rounded-xl",
        "border",
        "border-slate-200",
        "bg-slate-100",
        "lg:h-[380px]",
    ),
    mapTextWrapper: clsx(
        "flex",
        "h-full",
        "items-center",
        "justify-center",
    ),
    mapText: clsx(
        "text-sm",
        "text-slate-500",
    ),
    mapHint: clsx(
        "mt-2",
        "text-xs",
        "text-slate-500",
    ),
    readOnlyInput: clsx(
        "h-12",
        "w-full",
        "rounded-xl",
        "border",
        "border-slate-200",
        "bg-slate-50",
        "px-4",
        "text-sm",
        "text-slate-500",
        "outline-none",
        "sm:h-14",
    ),
    coordinatesGrid: clsx(
        "mt-4",
        "grid",
        "gap-4",
        "sm:grid-cols-2",
    ),
    fieldSpacing: clsx(
        "mt-4",
    ),
    actionsContainer: clsx(
        "sticky",
        "bottom-0",
        "z-20",
        "mt-6",
        "rounded-3xl",
        "border",
        "border-slate-200",
        "bg-white",
        "p-4",
        "shadow-sm",
    ),
    actionsWrapper: clsx(
        "flex",
        "flex-col-reverse",
        "gap-3",
        "sm:flex-row",
        "sm:justify-end",
    ),
    buttonSaveDraft: clsx(
        "h-12",
        "rounded-xl",
        "border",
        "border-teal-600",
        "px-6",
        "text-sm",
        "font-semibold",
        "text-teal-600",
        "transition",
        "hover:bg-teal-50",
        "sm:h-14",
    ),
    buttonSaveContinue: clsx(
        "h-12",
        "rounded-xl",
        "bg-teal-600",
        "px-6",
        "text-sm",
        "font-semibold",
        "text-white",
        "transition",
        "hover:bg-teal-700",
        "sm:h-14",
    ),
};
